stages:
  - Industrial CI
  - Downstream

# === Industrial CI ============================================================


ROS2 Jazzy:
  stage: Industrial CI
  trigger:
    include:
      - project: fb-fi/ops/templates/ci-templates
        ref: main
        file: .industrial_ci.template.yml
    strategy: depend
  variables:
    ROS_DISTRO: jazzy
    IMAGE_AMD64: 'rwthika/ros2-triton:jazzy'
    IMAGE_ARM64: 'rwthika/ros2-triton:jazzy'

# === Downstream ===============================================================

point_cloud_object_detection:
  stage: Downstream
  only:
    - main
  allow_failure: true
  trigger:
    project: fb-fi/its-modules/perception/point_cloud_object_detection
