stages:
  - Industrial CI
  - Downstream

# === Industrial CI ============================================================


ROS2 Humble:
  stage: Industrial CI
  trigger:
    include:
      - project: fb-fi/ops/templates/ci-templates
        ref: main
        file: .industrial_ci.template.yml
    strategy: depend
  variables:
    ROS_DISTRO: humble
    IMAGE_AMD64: 'rwthika/ros2-triton:humble'
    IMAGE_ARM64: 'rwthika/ros2-triton:humble-desktop-full-triton2.48.0'


ROS2 Iron:
  stage: Industrial CI
  trigger:
    include:
      - project: fb-fi/ops/templates/ci-templates
        ref: main
        file: .industrial_ci.template.yml
    strategy: depend
  variables:
    ROS_DISTRO: iron
    IMAGE_AMD64: 'rwthika/ros2-triton:iron'
    IMAGE_ARM64: 'rwthika/ros2-triton:iron-desktop-full-triton2.48.0'

ROS2 Jazzy:
  stage: Industrial CI
  trigger:
    include:
      - project: fb-fi/ops/templates/ci-templates
        ref: main
        file: .industrial_ci.template.yml
    strategy: depend
  variables:
    ROS_DISTRO: jazzy
    IMAGE_AMD64: 'rwthika/ros2-triton:jazzy'
    DISABLE_ARCH_ARM64: 'true'

# === Downstream ===============================================================

point_cloud_object_detection:
  stage: Downstream
  only:
    - main
  allow_failure: true
  trigger:
    project: fb-fi/its-modules/perception/point_cloud_object_detection
