triton_cpp: triton_cpp::TritonInterface Class Reference
triton_cpp::TritonInterface Class Reference
Synchronous, typed interface to one model served by Triton.
#include <triton_interface.hpp>
Public Member Functions
TritonInterface (const std::string &model_name, const std::string &model_version, const std::string &server_url, bool shm, bool variable_input_size=false, bool retry_connection=false, double client_timeout_s=0.0, bool cuda_input_shm=false)
Connect to Triton and query metadata for one model.
void initInOutputs (std::optional< std::map< std::string, std::vector< int64_t > > > special_output_shapes, std::optional< std::map< std::string, std::vector< int64_t > > > special_input_shapes=std::nullopt)
Creates all input and output buffers for the model, based on the model metadata.
void infer ()
Run synchronous inference with the data currently stored in the input buffers.
template<typename T >
VectorType< T > getInputTensor (const std::string &name, int64_t rows)
Get a view to the InputBuffer, interpreted as a Vector.
template<typename T >
MatrixType< T > getInputTensor (const std::string &name, int64_t rows, int64_t cols)
Get a view to the InputBuffer, interpreted as a Matrix.
template<typename T , typename... DimType>
TensorType< T, sizeof...(DimType)+3 > getInputTensor (const std::string &name, int64_t dim0, int64_t dim1, int64_t dim2, DimType... dims)
Get a view to the InputBuffer, interpreted as a Tensor of rank >=3.
std::pair< uint8_t *, std::size_t > getInputTensor (const std::string &name)
Get the raw input buffer.
bool usesCudaInputSharedMemory () const
Whether input tensors are currently backed by Triton CUDA shared memory.
std::pair< uint8_t *, std::size_t > getInputTensorDevice (const std::string &name)
Get the device pointer for a CUDA shared-memory-backed input tensor.
void copyInputTensorToDevice (const std::string &name, const void *host_data, std::size_t bytes)
Copy host data into a CUDA shared-memory-backed input tensor.
template<typename T >
VectorType< const T > getOutputTensor (const std::string &name, int64_t rows) const
Get a view to the OutputBuffer, interpreted as a Vector.
template<typename T >
MatrixType< const T > getOutputTensor (const std::string &name, int64_t rows, int64_t cols) const
Get a view to the OutputBuffer, interpreted as a Matrix.
template<typename T , typename... DimType>
TensorType< const T, sizeof...(DimType)+3 > getOutputTensor (const std::string &name, int64_t dim0, int64_t dim1, int64_t dim2, DimType... dims) const
Get a view to the OutputBuffer, interpreted as a Tensor of rank >=3.
std::pair< const uint8_t *, std::size_t > getOutputTensor (const std::string &name) const
Get the raw output buffer and its size.
std::string getModelInfo () const
Get a description of the model's in and outputs as human-readable text.
std::size_t nInputs () const
Get the number of inputs.
std::size_t nOutputs () const
Get the number of outputs.
std::vector< int64_t > getInputShape (const std::string &name) const
Get the Input Shape of a tensor.
std::vector< int64_t > getOutputShape (const std::string &name) const
Get the Output Shape of a tensor.
Lifetime
TritonInterface (const TritonInterface &)=delete
Copy construction is disabled because the interface owns registrations and buffers.
TritonInterface & operator= (const TritonInterface &)=delete
Copy assignment is disabled because the interface owns registrations and buffers.
TritonInterface (TritonInterface &&)=delete
Move construction is disabled to keep registered buffer addresses stable.
TritonInterface & operator= (TritonInterface &&)=delete
Move assignment is disabled to keep registered buffer addresses stable.
~TritonInterface ()
Unregister shared-memory regions owned by this interface.
Detailed Description
Synchronous, typed interface to one model served by Triton.
The interface owns the Triton gRPC client, model input/output descriptors, and optional system or CUDA shared-memory registrations. Call initInOutputs() before accessing tensors or performing inference.
Definition at line 36 of file triton_interface.hpp.
Constructor & Destructor Documentation
TritonInterface() [1/3]
triton_cpp::TritonInterface::TritonInterface (const std::string & model_name, const std::string & model_version, const std::string & server_url, bool shm, bool variable_input_size = false, bool retry_connection = false, double client_timeout_s = 0.0, bool cuda_input_shm = false) inline
Connect to Triton and query metadata for one model.
Parameters
model_name Name of the served model.
model_version Model version, such as "1".
server_url Triton gRPC endpoint, such as "127.0.0.1:8001".
shm Use POSIX shared memory for inputs and outputs.
variable_input_size Recreate standard input buffers when callers request new shapes.
retry_connection Retry client creation and model metadata queries once per second.
client_timeout_s Per-inference client timeout in seconds; zero disables the timeout.
cuda_input_shm Use CUDA IPC shared memory for inputs. Outputs still follow shm.
Exceptions
std::invalid_argument for incompatible options or a negative timeout.
std::runtime_error if the server connection, model query, or requested CUDA support fails.
Definition at line 52 of file triton_interface.hpp.
      : options_{model_name}, shm_{shm}, variable_input_size_{variable_input_size}, cuda_input_shm_requested_{cuda_input_shm} {
    if ((shm || cuda_input_shm) && variable_input_size) {
      throw std::invalid_argument("Variable input size and shared memory cannot be combined");
    }
    options_.model_version_ = model_version;
    if (client_timeout_s < 0.0) {
      throw std::invalid_argument("client_timeout_s must be >= 0.0");
    }
    options_.client_timeout_ = static_cast<decltype(options_.client_timeout_)>(client_timeout_s * 1e6);
    triton::client::Error err;
    err = triton::client::InferenceServerGrpcClient::Create(&triton_client_, server_url, false);
    while (retry_connection && !err.IsOk()) {
      std::cerr << "Failed to create Triton client: " << err.Message() << ". Retrying..." << std::endl;
      std::this_thread::sleep_for(std::chrono::seconds(1));
      err = triton::client::InferenceServerGrpcClient::Create(&triton_client_, server_url, false);
    }
    if (!err.IsOk()) {
      throw std::runtime_error("Failed to create Triton client: " + err.Message());
    }
    inference::ModelConfigResponse model_config;
    err = triton_client_->ModelConfig(&model_config, model_name, model_version);
    while (retry_connection && !err.IsOk()) {
      std::cerr << "Failed to get model config from Triton server: " << err.Message() << ". Retrying..." << std::endl;
      std::this_thread::sleep_for(std::chrono::seconds(1));
      err = triton_client_->ModelConfig(&model_config, model_name, model_version);
    }
    if (!err.IsOk()) {
      throw std::runtime_error("Failed to get model config from Triton server: " + err.Message());
    }
    std::tie(input_metadata_, output_metadata_) = build_model_info(model_config);
    if (cuda_input_shm_requested_) {
#if defined(TRITON_CPP_ENABLE_CUDA_SHM)
      inference::ServerMetadataResponse server_metadata;
      const auto metadata_status = triton_client_->ServerMetadata(&server_metadata);
      if (!metadata_status.IsOk()) {
        throw std::runtime_error(
            "CUDA input shared memory was requested, but Triton server metadata could not be "
            "queried: " +
            metadata_status.Message());
      } else {
        const bool server_supports_cuda_shm = std::find(server_metadata.extensions().begin(), server_metadata.extensions().end(),
                                                        "cuda_shared_memory") != server_metadata.extensions().end();
        std::string reason;
        if (!server_supports_cuda_shm) {
          throw std::runtime_error(
              "CUDA input shared memory was requested, but the Triton server does not advertise "
              "cuda_shared_memory support");
        } else if (!LocalCudaSharedMemorySupported(&reason)) {
          throw std::runtime_error(
              "CUDA input shared memory was requested, but local CUDA shared memory is not "
              "available: " +
              reason);
        } else {
          cuda_input_shm_enabled_ = true;
        }
      }
#else
      throw std::runtime_error(
          "CUDA input shared memory was requested, but triton_cpp was built without CUDA SHM "
          "support");
#endif
    }
  }
References triton_cpp::LocalCudaSharedMemorySupported().
TritonInterface() [2/3]
triton_cpp::TritonInterface::TritonInterface (const TritonInterface &) delete
Copy construction is disabled because the interface owns registrations and buffers.
TritonInterface() [3/3]
triton_cpp::TritonInterface::TritonInterface (TritonInterface &&) delete
Move construction is disabled to keep registered buffer addresses stable.
~TritonInterface()
triton_cpp::TritonInterface::~TritonInterface () inline
Unregister shared-memory regions owned by this interface.
Definition at line 137 of file triton_interface.hpp.
{ releaseSharedMemoryRegistrations(); };
Member Function Documentation
copyInputTensorToDevice()
void triton_cpp::TritonInterface::copyInputTensorToDevice (const std::string & name, const void * host_data, std::size_t bytes) inline
Copy host data into a CUDA shared-memory-backed input tensor.
Parameters
name Name of the input tensor.
host_data Pointer to the host buffer to copy from.
bytes Number of bytes to copy. Must exactly match the input tensor size.
Exceptions
std::invalid_argument if the tensor is not CUDA-backed, the byte size does not match, or triton_cpp was built without CUDA SHM support.
std::runtime_error if the underlying CUDA copy fails.
Definition at line 376 of file triton_interface.hpp.
{
#if defined(TRITON_CPP_ENABLE_CUDA_SHM)
    auto& input = inputs_.at(name);
    if (!input.isDeviceBacked()) {
      throw std::invalid_argument("Input tensor '" + name + "' is not backed by CUDA shared memory");
    }
    if (bytes != input.data_raw_size) {
      throw std::invalid_argument("Input tensor '" + name + "' byte size mismatch for host-to-device copy");
    }
    throw_on_cuda_error(cudaMemcpy(input.device_data_raw, host_data, bytes, cudaMemcpyHostToDevice), "cudaMemcpy");
#else
    // Suppress unused-parameter warnings when CUDA SHM support is not compiled in.
    (void)name;
    (void)host_data;
    (void)bytes;
    throw std::invalid_argument("triton_cpp was built without CUDA SHM support");
#endif
  }
References triton_cpp::throw_on_cuda_error().
getInputShape()
std::vector< int64_t > triton_cpp::TritonInterface::getInputShape (const std::string & name) const inline
Get the Input Shape of a tensor.
Parameters
name name of the input tensor
Returns
std::vector<int64_t> shape of the input tensor
Exceptions
std::invalid_argument if the input name is not found in the model metadata
Definition at line 512 of file triton_interface.hpp.
{
    auto it = input_metadata_.find(name);
    if (it == input_metadata_.end()) {
      throw std::invalid_argument("Input name not found in model metadata: " + name);
    }
    return it->second.shape;
  }
getInputTensor() [1/4]
std::pair< uint8_t *, std::size_t > triton_cpp::TritonInterface::getInputTensor (const std::string & name) inline
Get the raw input buffer.
Parameters
name name of the input
Returns
std::pair<uint8_t*, std::size_t> Pointer to the host-mappable input buffer and its size in bytes.
Exceptions
std::invalid_argument if variable input size is enabled and this input has not been created yet, or if the input is not host-mappable.
Definition at line 333 of file triton_interface.hpp.
{
    if (variable_input_size_ && inputs_.count(name) == 0) {
      throw(std::invalid_argument("Variable input size is enabled, but no size was provided for input " + name));
    }
    auto& input = inputs_[name];
    if (!input.isHostMappable()) {
      throw std::invalid_argument("Input tensor '" + name + "' is backed by CUDA shared memory and is not host-mappable");
    }
    return {input.data_raw, input.data_raw_size};
  }
getInputTensor() [2/4]
template<typename T , typename... DimType> TensorType< T, sizeof...(DimType)+3 > triton_cpp::TritonInterface::getInputTensor (const std::string & name, int64_t dim0, int64_t dim1, int64_t dim2, DimType... dims) inline
Get a view to the InputBuffer, interpreted as a Tensor of rank >=3.
Template Parameters
T Scalar data type
Parameters
name name of the input
dim0 size of the tensor.
dim1 size of the tensor.
dim2 size of the tensor.
dims size of the tensor (arbitrary count).
Exceptions
std::invalid_argument if the size of the input buffer does not match the requested size
Returns
TensorType<T> the requested Eigen::TensorMap
Definition at line 305 of file triton_interface.hpp.
{
    if (variable_input_size_) {
      CreateInputTensor(name, dim0, dim1, dim2, dims...);
    }
    auto& input = inputs_[name];
    if (!input.isHostMappable()) {
      throw std::invalid_argument("Input tensor '" + name + "' is backed by CUDA shared memory and is not host-mappable");
    }
    if (((dim0 * dim1 * dim2) * ... * dims) * sizeof(T) != input.data_raw_size) {
      std::stringstream ss;
      // Print the further dims, separated by commas
      ss << name << ": dims: " << dim0 << ", " << dim1 << ", " << dim2;
      ((ss << ", " << dims), ...);
      ss << " sizeof(T): " << sizeof(T) << " input.data_raw_size: " << input.data_raw_size << std::endl;
      throw std::invalid_argument("Invalid input tensor size: " + ss.str());
    }
    return TensorType<T, sizeof...(dims) + 3>{reinterpret_cast<T*>(input.data_raw), dim0, dim1, dim2, dims...};
  }
getInputTensor() [3/4]
template<typename T > VectorType< T > triton_cpp::TritonInterface::getInputTensor (const std::string & name, int64_t rows) inline
Get a view to the InputBuffer, interpreted as a Vector.
Template Parameters
T Scalar data type
Parameters
name name of the input
rows size of the vector.
Exceptions
std::invalid_argument if the size of the input buffer does not match the requested size
Returns
VectorType<T> the requested Eigen::Map
Definition at line 247 of file triton_interface.hpp.
{
    if (variable_input_size_) {
      CreateInputTensor(name, rows);
    }
    auto& input = inputs_[name];
    if (!input.isHostMappable()) {
      throw std::invalid_argument("Input tensor '" + name + "' is backed by CUDA shared memory and is not host-mappable");
    }
    if (rows * sizeof(T) != input.data_raw_size) {
      std::stringstream ss;
      ss << name << ": rows: " << rows << " sizeof(T): " << sizeof(T) << " input.data_raw_size: " << input.data_raw_size
         << std::endl;
      throw std::invalid_argument("Invalid input tensor size: " + ss.str());
    }
    return VectorType<T>{reinterpret_cast<T*>(input.data_raw), rows};
  }
getInputTensor() [4/4]
template<typename T > MatrixType< T > triton_cpp::TritonInterface::getInputTensor (const std::string & name, int64_t rows, int64_t cols) inline
Get a view to the InputBuffer, interpreted as a Matrix.
Template Parameters
T Scalar data type
Parameters
name name of the input
rows size of the matrix.
cols size of the matrix.
Exceptions
std::invalid_argument if the size of the input buffer does not match the requested size
Returns
MatrixType<T> the requested Eigen::Map
Definition at line 275 of file triton_interface.hpp.
{
    if (variable_input_size_) {
      CreateInputTensor(name, rows, cols);
    }
    auto& input = inputs_[name];
    if (!input.isHostMappable()) {
      throw std::invalid_argument("Input tensor '" + name + "' is backed by CUDA shared memory and is not host-mappable");
    }
    if (rows * cols * sizeof(T) != input.data_raw_size) {
      std::stringstream ss;
      ss << name << ": rows: " << rows << " cols: " << cols << " sizeof(T): " << sizeof(T)
         << " input.data_raw_size: " << input.data_raw_size << std::endl;
      throw std::invalid_argument("Invalid input tensor size: " + ss.str());
    }
    return MatrixType<T>{reinterpret_cast<T*>(input.data_raw), rows, cols};
  }
getInputTensorDevice()
std::pair< uint8_t *, std::size_t > triton_cpp::TritonInterface::getInputTensorDevice (const std::string & name) inline
Get the device pointer for a CUDA shared-memory-backed input tensor.
Parameters
name Name of the input tensor.
Returns
std::pair<uint8_t*, std::size_t> Device pointer and tensor size in bytes.
Exceptions
std::invalid_argument if the input is not backed by CUDA shared memory.
Definition at line 358 of file triton_interface.hpp.
{
    auto& input = inputs_.at(name);
    if (!input.isDeviceBacked()) {
      throw std::invalid_argument("Input tensor '" + name + "' is not backed by CUDA shared memory");
    }
    return {input.device_data_raw, input.data_raw_size};
  }
getModelInfo()
std::string triton_cpp::TritonInterface::getModelInfo () const inline
Get a description of the model's in and outputs as human-readable text.
Returns
std::string model info
Definition at line 489 of file triton_interface.hpp.
{ return model_info_; }
getOutputShape()
std::vector< int64_t > triton_cpp::TritonInterface::getOutputShape (const std::string & name) const inline
Get the Output Shape of a tensor.
Parameters
name name of the output tensor
Returns
std::vector<int64_t> shape of the output tensor
Exceptions
std::invalid_argument if the output name is not found in the model metadata
Definition at line 527 of file triton_interface.hpp.
{
    auto it = output_metadata_.find(name);
    if (it == output_metadata_.end()) {
      throw std::invalid_argument("Output name not found in model metadata: " + name);
    }
    return it->second.shape;
  }
getOutputTensor() [1/4]
std::pair< const uint8_t *, std::size_t > triton_cpp::TritonInterface::getOutputTensor (const std::string & name) const inline
Get the raw output buffer and its size.
Parameters
name Name of the output tensor.
Returns
Pointer to immutable output data and its size in bytes.
Exceptions
std::out_of_range if name is unknown when shared memory is enabled.
Definition at line 469 of file triton_interface.hpp.
{
    const uint8_t* raw_data_buf{nullptr};
    std::size_t raw_data_size;
    if (shm_) {
      auto shm = outputs_.at(name);
      std::size_t offset;
      std::string shm_name;
      shm->SharedMemoryInfo(&shm_name, &raw_data_size, &offset);
      raw_data_buf = output_shm_->getAddress() + offset;
    } else {
      results_->RawData(name, &raw_data_buf, &raw_data_size);
    }
    return {raw_data_buf, raw_data_size};
  }
getOutputTensor() [2/4]
template<typename T , typename... DimType> TensorType< const T, sizeof...(DimType)+3 > triton_cpp::TritonInterface::getOutputTensor (const std::string & name, int64_t dim0, int64_t dim1, int64_t dim2, DimType... dims) const inline
Get a view to the OutputBuffer, interpreted as a Tensor of rank >=3.
Template Parameters
T Scalar data type
Parameters
name name of the output
dim0 size of the tensor.
dim1 size of the tensor.
dim2 size of the tensor.
dims size of the tensor (arbitrary count).
Exceptions
std::invalid_argument if the size of the output buffer does not match the requested size
Returns
TensorType<const T> the requested Eigen::TensorMap
Definition at line 450 of file triton_interface.hpp.
{
    auto [raw_data_buf, raw_data_size] = getOutputTensor(name);
    if (raw_data_size != ((dim0 * dim1 * dim2) * ... * dims) * sizeof(T)) {
      std::stringstream ss;
      ss << name << ": dims: " << dim0 << ", " << dim1 << ", " << dim2;
      ((ss << ", " << dims), ...);
      ss << " sizeof(T): " << sizeof(T) << " raw_data_size: " << raw_data_size << std::endl;
      throw std::invalid_argument("Invalid output tensor size: " + ss.str());
    }
    return TensorType<const T, sizeof...(dims) + 3>{reinterpret_cast<const T*>(raw_data_buf), dim0, dim1, dim2, dims...};
  }
References getOutputTensor().
getOutputTensor() [3/4]
template<typename T > VectorType< const T > triton_cpp::TritonInterface::getOutputTensor (const std::string & name, int64_t rows) const inline
Get a view to the OutputBuffer, interpreted as a Vector.
Template Parameters
T Scalar data type
Parameters
name name of the output
rows size of the vector.
Exceptions
std::invalid_argument if the size of the input buffer does not match the requested size
Returns
VectorType<const T> the requested Eigen::Map
Definition at line 405 of file triton_interface.hpp.
{
    auto [raw_data_buf, raw_data_size] = getOutputTensor(name);
    if (raw_data_size != rows * sizeof(T)) {
      std::stringstream ss;
      ss << name << ": rows: " << rows << " sizeof(T): " << sizeof(T) << " raw_data_size: " << raw_data_size << std::endl;
      throw std::invalid_argument("Invalid output tensor size: " + ss.str());
    }
    return VectorType<const T>{reinterpret_cast<const T*>(raw_data_buf), rows};
  }
References getOutputTensor().
Referenced by getOutputTensor(), getOutputTensor(), and getOutputTensor().
getOutputTensor() [4/4]
template<typename T > MatrixType< const T > triton_cpp::TritonInterface::getOutputTensor (const std::string & name, int64_t rows, int64_t cols) const inline
Get a view to the OutputBuffer, interpreted as a Matrix.
Template Parameters
T Scalar data type
Parameters
name name of the output
rows size of the matrix.
cols size of the matrix.
Exceptions
std::invalid_argument if the size of the output buffer does not match the requested size
Returns
MatrixType<const T> the requested Eigen::Map
Definition at line 426 of file triton_interface.hpp.
{
    auto [raw_data_buf, raw_data_size] = getOutputTensor(name);
    if (raw_data_size != rows * cols * sizeof(T)) {
      std::stringstream ss;
      ss << name << ": rows: " << rows << " cols: " << cols << " sizeof(T): " << sizeof(T) << " raw_data_size: " << raw_data_size
         << std::endl;
      throw std::invalid_argument("Invalid output tensor size: " + ss.str());
    }
    return MatrixType<const T>{reinterpret_cast<const T*>(raw_data_buf), rows, cols};
  }
References getOutputTensor().
infer()
void triton_cpp::TritonInterface::infer () inline
Run synchronous inference with the data currently stored in the input buffers.
Returned output views remain valid until the next call to infer().
Exceptions
std::runtime_error if Triton rejects or fails the inference request.
Definition at line 222 of file triton_interface.hpp.
               {
    if (variable_input_size_) {
      raw_inputs_.clear();
      for (const auto& input : inputs_) {
        raw_inputs_.push_back(input.second.input.get());
      }
    }
    triton::client::InferResult* raw_results{nullptr};
    auto status = triton_client_->Infer(&raw_results, options_, raw_inputs_, raw_outputs_);
    if (!status.IsOk()) {
      throw(std::runtime_error("ModelInfer failed: " + status.Message()));
    }
    results_.reset(raw_results);
  };
initInOutputs()
void triton_cpp::TritonInterface::initInOutputs (std::optional< std::map< std::string, std::vector< int64_t > > > special_output_shapes, std::optional< std::map< std::string, std::vector< int64_t > > > special_input_shapes = std::nullopt) inline
Creates all input and output buffers for the model, based on the model metadata.
Parameters
special_output_shapes Some models don't know their output shape, i.e. it is given as -1. In this case, you must provide the correct shape here.
special_input_shapes Some models don't know their input shape, i.e. it is given as -1. In this case, you must provide the correct shape here.
Exceptions
std::invalid_argument if a provided input or output name is unknown.
std::runtime_error if shared-memory setup was requested but initialization fails.
Definition at line 148 of file triton_interface.hpp.
{
    releaseSharedMemoryRegistrations();
    input_shm_.reset();
#if defined(TRITON_CPP_ENABLE_CUDA_SHM)
    input_cuda_shm_.reset();
#endif
    output_shm_.reset();
    inputs_.clear();
    outputs_.clear();
    if (special_input_shapes.has_value()) {
      for (const auto& [name, shape] : special_input_shapes.value()) {
        auto it = input_metadata_.find(name);
        if (it == input_metadata_.end()) {
          throw std::invalid_argument("Input name not found in model metadata: " + name);
        }
        const auto datatype = it->second.datatype;
        input_metadata_.erase(it);
        input_metadata_.emplace(name, InputOutputMetaData{shape, datatype});
      }
    }
    if (special_output_shapes.has_value()) {
      for (const auto& [name, shape] : special_output_shapes.value()) {
        auto it = output_metadata_.find(name);
        if (it == output_metadata_.end()) {
          throw std::invalid_argument("Output name not found in model metadata: " + name);
        }
        const auto datatype = it->second.datatype;
        output_metadata_.erase(it);
        output_metadata_.emplace(name, InputOutputMetaData{shape, datatype});
      }
    }
    if (!variable_input_size_) {
      if (cuda_input_shm_enabled_) {
        try {
          setup_cuda_shm_inputs(input_metadata_);
        } catch (const std::exception& e) {
          throw std::runtime_error("CUDA input shared memory was requested, but initialization failed: " + std::string(e.what()));
        }
      } else if (shm_) {
        setup_shm_inputs(input_metadata_);
      } else {
        setup_standard_inputs(input_metadata_);
      }
    }
    if (shm_) {
      setup_shm_outputs(output_metadata_);
    } else {
      setup_standard_outputs(output_metadata_);
    }
    // Also store the raw pointers to in/outputs in vectors, as required by the Triton client
    // We don't have to delete these anywhere, as they are managed by the respective shared pointers
    if (!variable_input_size_) {
      raw_inputs_.clear();
      for (const auto& input : inputs_) {
        raw_inputs_.push_back(input.second.input.get());
      }
    }
    raw_outputs_.clear();
    for (const auto& output : outputs_) {
      raw_outputs_.push_back(output.second.get());
    }
  }
nInputs()
std::size_t triton_cpp::TritonInterface::nInputs () const inline
Get the number of inputs.
Returns
std::size_t
Definition at line 496 of file triton_interface.hpp.
{ return input_metadata_.size(); }
nOutputs()
std::size_t triton_cpp::TritonInterface::nOutputs () const inline
Get the number of outputs.
Returns
std::size_t
Definition at line 503 of file triton_interface.hpp.
{ return output_metadata_.size(); }
operator=() [1/2]
TritonInterface & triton_cpp::TritonInterface::operator= (const TritonInterface &) delete
Copy assignment is disabled because the interface owns registrations and buffers.
operator=() [2/2]
TritonInterface & triton_cpp::TritonInterface::operator= (TritonInterface &&) delete
Move assignment is disabled to keep registered buffer addresses stable.
usesCudaInputSharedMemory()
bool triton_cpp::TritonInterface::usesCudaInputSharedMemory () const inline
Whether input tensors are currently backed by Triton CUDA shared memory.
Returns
true if CUDA shared memory is enabled for inputs, otherwise false.
Definition at line 349 of file triton_interface.hpp.
{ return cuda_input_shm_enabled_; }
The documentation for this class was generated from the following file:
include/triton_cpp/triton_interface.hpp